file_format: "1"
id: knobold
name: Knobold
type: shield
url: https://github.com/cinicle/zmk-config-knobold
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings: