manifest:
  defaults:
    remote: zmkfirmware
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      path: zmk
      remote: zmkfirmware
      revision: main
  self:
    path: config
    west-commands: zmk/west/west-commands.yml