name: Build Firmware

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install West and dependencies
      run: |
        pip install --upgrade pip
        pip install west
        west init --manifest-rev=main
        west update

    - name: Build Firmware
      run: |
        cd zmk
        source zephyr/zephyr-env.sh
        west build -b nice_nano_v2 -- -DSHIELD="Knobold nice_view_adapter nice_view"
