name: Build Firmware

on:
  push:
    branches:
      - master
    paths:
      - 'config/boards/shields/Knobold/**' #match your shield's conf path
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install West and dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install west
        west init -l zmk
        west update

    - name: Build Firmware
      run: |
        cd zmk
        source zephyr/zephyr-env.sh
        west build -b nice_nano_v2 -- -DSHIELD="Knobold nice_view_adapter nice_view"